
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/conda/cmake-3.27.0-rc3-linux-x86_64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.10.102.1-microsoft-standard-WSL2 - x86_64
...
